### ISSUE TITLE
Fortified Tier Decreases Armor Under Certain Conditions

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Globox1997/tiered#20]
This may actually be a Minecraft bug, as I am not sure how this could be caused by Tiered. I have linked a video that shows the issue, as it's a bit hard to explain. Basically, the Fortified Tier seems to remove more armor than it gives, if you have a lot of armor already or under certain circumstances? Sometimes Fortified also works correctly, but the issue it is easily replicated as shown in my video.

https://www.youtube.com/watch?v=ngQIaBdxJ7A

**Comment by Atla01** [comment]
I have this problem too.
I will add that if you put on armor for + HP or + armor, then with one more item for the same buffs, the buff of the latter is selected. Maybe he behaves this way because additional mods are needed to correctly display HP or Armor?
This mod brings a good idea, but this bug spoils the experience. The way I described it may not be entirely accurate as I used a translator.

**Comment by Globox1997** [comment]
this got fixed with the latest commits
